name: Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Login 
      env:
        DOCKER_USER: ${{ secrets.REGISTRY_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
 #   - uses: Azure/docker-login@v1
 #     with:
 #       login-server: vsazurecr.azurecr.io
 #       username: ${{ secrets.REGISTRY_USERNAME }}
 #       password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build dotnetapp code
      run: |
         docker build . -t vsazurecr.azurecr.io/vsdotnetapp:${{ github.sha }}
         
